// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB57TvKZUIjNY_vanJqUNibXmfahHD1HOo',
    appId: '1:940006126022:android:523315922914067981c2c7',
    messagingSenderId: '940006126022',
    projectId: 'quiz-app-20ae7',
    storageBucket: 'quiz-app-20ae7.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAi7VO2J0iT9PyxkzNsnK8D84jbMRlJvM',
    appId: '1:940006126022:ios:e7b936cb1f5b13ac81c2c7',
    messagingSenderId: '940006126022',
    projectId: 'quiz-app-20ae7',
    storageBucket: 'quiz-app-20ae7.appspot.com',
    androidClientId:
        '940006126022-afk4b46bnpi3mk4ri7vdvrhpsg19vdnk.apps.googleusercontent.com',
    iosClientId:
        '940006126022-5u20h1tg0ke2rd1nehceitd0e36uk4pa.apps.googleusercontent.com',
    iosBundleId: 'perfectline.io.rando',
  );
}
